version: "3.1"

services:
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "mysqlbigdatalol"
            MYSQL_USER: "megadados"
            MYSQL_PASSWORD: "megadados2020"
        ports:
            - "33062:3306"
        volumes:
            - ./db-files:/var/lib/mysql
            - .:/home/megadados
